version: "3"
services:
  php:
    build: docker/php
    container_name: php
    tty: true
    volumes:
      - ./frameworks:/var/www/html
    ports:
      - 12000:12000
      - 12001:12001
      - 12100:12100
      - 12200:12200
  selenium:
    build: docker/selenium
    container_name: selenium
    tty: true
    ports:
      - 4444:4444
    environment:
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      - SCREEN_DPI=74

